# Generated by Django 2.0.2 on 2018-07-23 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180723_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmovie',
            name='p_rating',
            field=models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
