# Generated by Django 2.0.2 on 2018-07-27 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180724_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='n_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ratingmovie',
            name='p_rating',
            field=models.IntegerField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
